AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'rest_weather_api

  Sample SAM Template for rest_weather_api

  '
Globals:
  Function:
    Runtime: python3.10
    CodeUri: src/
    Timeout: 3
    MemorySize: 128
    Environment:
      Variables:
        TABLE_NAME:
          Ref: WeatherTable
  Api:
    EndpointConfiguration: REGIONAL
    TracingEnabled: true
    Cors:
      AllowMethods: '''OPTIONS,POST,GET,PUT,DELETE'''
      AllowHeaders: '''Content-Type'''
      AllowOrigin: '''*'''
Resources:
  WeatherApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Description: serverless api for weather application
  CreateWeather:
    Type: AWS::Serverless::Function
    Description: Lambda function inserts weather data into DynamoDB table
    Properties:
      FunctionName: CreateWeatherLambda
      Handler: create_weather.lambda_handler
      Policies:
        DynamoDBCrudPolicy:
          TableName:
            Ref: WeatherTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /create-weather
            Method: POST
            RestApiId:
              Ref: WeatherApi
      CodeUri: CreateWeather
      Layers:
      - Fn::GetAtt:
        - AwsSamAutoDependencyLayerNestedStack
        - Outputs.CreateWeathera340834fDepLayer
    Metadata:
      SamResourceId: CreateWeather
  WeatherTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  AwsSamAutoDependencyLayerNestedStack:
    DeletionPolicy: Delete
    Metadata:
      CreatedBy: AWS SAM CLI sync command
    Properties:
      TemplateURL: /Users/rosius/Documents/rest_weather_api/.aws-sam/auto-dependency-layer/adl_nested_template.yaml
    Type: AWS::CloudFormation::Stack
Outputs:
  WeatherApi:
    Description: API Gateway endpoint URL for dev stage for create weather function
    Value:
      Fn::Sub: https://${WeatherApi}.execute-api.${AWS::Region}.amazonaws.com/dev/
  CreateWeatherFunction:
    Description: Create Weather Lambda Function ARN
    Value:
      Fn::GetAtt:
      - CreateWeather
      - Arn
